### ISSUE TITLE
Add bootstrap code for front end application

### ISSUE THREAD

**Issue by as-ajitsingh** [bored-engineers/the-retro-app#3]
This should contain package scripts for - 

- [ ] Linting 

- [x] Compile and Build

- [x] Unit Testing

- [x] Serving the content using static server

**Comment by amiteshtoharya4** [comment]
I have merged the MR.
I used the create-react-app template and it has some pretty interesting things implemented and I could not figure out everything.
Also, could not take care of the linting for the code.
We will have to cover it in another story.

The code changes done in this MR might need some cleaning which will be done in corresponding stories.
