### ISSUE TITLE
Support for anonymous user

### ISSUE THREAD

**Issue by as-ajitsingh** [bored-engineers/the-retro-app#64]
- User should be anonymous

**Comment by amiteshtoharya4** [comment]
I have picked this up holding on the delete ui for now. I was thinking that we should use a uuid for the user. 
The idea with dummy name will have one thing that is that after we get the random dummy name then we will have to check if there is a user with that name and then assign another name.

With uuid, the check for that is not needed

**Comment by amiteshtoharya4** [comment]
Also I am looking to do this is 2 cuts,

1. Anyone joining the board will be assumed as a new user and assigned a new uuid. This can lead to a case that once you rejoin you are assigned a new userId which will hamper the votes thing.

2. We can put some data in the localStorage to get if someone has rejoined then we can reassign the userId and the votes should be working
